# This code is part of Cqlib.
#
# (C) Copyright China Telecom Quantum Group 2026
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http:#www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

"""
Tests for QASM2 dump (export) functionality.

Test Coverage:
- QASM2 string generation (dumps)
- QASM2 file saving (dump)
- Standard gates output verification
- Parametric gates with expressions
- Directives (measure, barrier, reset)
- Custom gate definitions
- Extended gates (crx, cry, rzz, etc.)
"""

import tempfile
import os
from cqlib.circuit import Circuit, Parameter
from cqlib.ir.qasm2 import dumps, dump


class TestQasm2Dumps:
    """Test QASM2 generation with exact output verification."""

    def test_dumps_empty_circuit(self):
        """Generate QASM for empty circuit with correct header."""
        c = Circuit(1)
        qasm = dumps(c)

        # Verify header structure exactly
        lines = qasm.strip().split("\n")
        assert lines[0] == "// This file is auto-generated by Cqlib."
        assert lines[1] == "OPENQASM 2.0;"
        assert lines[2] == 'include "qelib1.inc";'
        assert "qreg q[1];" in qasm
        # Note: creg is only created for qubits used in conditional operations

    def test_dumps_single_qubit_gates(self):
        """Generate QASM for single-qubit gates with exact verification."""
        c = Circuit(1)
        c.h(0)
        c.x(0)
        c.y(0)
        c.z(0)

        qasm = dumps(c)
        lines = [
            line.strip() for line in qasm.split("\n") if line.strip().endswith(";")
        ]

        # Find gate lines (after header and register declarations)
        gate_lines = [
            line for line in lines if line.startswith(("h ", "x ", "y ", "z "))
        ]
        assert gate_lines == ["h q[0];", "x q[0];", "y q[0];", "z q[0];"]

    def test_dumps_phase_gates(self):
        """Generate QASM for phase gates (S, Sdg, T, Tdg)."""
        c = Circuit(1)
        c.s(0)
        c.sdg(0)
        c.t(0)
        c.tdg(0)

        qasm = dumps(c)
        lines = [
            line.strip() for line in qasm.split("\n") if line.strip().endswith(";")
        ]

        gate_lines = [
            line for line in lines if line.startswith(("s ", "sdg ", "t ", "tdg "))
        ]
        assert gate_lines == ["s q[0];", "sdg q[0];", "t q[0];", "tdg q[0];"]

    def test_dumps_cnot(self):
        """Generate QASM for CNOT gate."""
        c = Circuit(2)
        c.cx(0, 1)

        qasm = dumps(c)
        assert "cx q[0],q[1];" in qasm

    def test_dumps_two_qubit_gates(self):
        """Generate QASM for two-qubit gates (CY, CZ, SWAP)."""
        c = Circuit(2)
        c.cy(0, 1)
        c.cz(0, 1)
        c.swap(0, 1)

        qasm = dumps(c)
        lines = [
            line.strip() for line in qasm.split("\n") if line.strip().endswith(";")
        ]

        gate_lines = [
            line for line in lines if line.startswith(("cy ", "cz ", "swap "))
        ]
        assert gate_lines == ["cy q[0],q[1];", "cz q[0],q[1];", "swap q[0],q[1];"]

    def test_dumps_toffoli(self):
        """Generate QASM for CCX (Toffoli) gate."""
        c = Circuit(3)
        c.ccx(0, 1, 2)

        qasm = dumps(c)
        assert "ccx q[0],q[1],q[2];" in qasm

    def test_dumps_parametric_gates(self):
        """Generate QASM for parametric rotation gates."""
        c = Circuit(1)
        c.rx(0, 0.5)
        c.ry(0, 0.3)
        c.rz(0, 0.7)

        qasm = dumps(c)
        lines = [
            line.strip() for line in qasm.split("\n") if line.strip().endswith(";")
        ]

        gate_lines = [line for line in lines if line.startswith(("rx(", "ry(", "rz("))]
        assert gate_lines == ["rx(0.5) q[0];", "ry(0.3) q[0];", "rz(0.7) q[0];"]

    def test_dumps_u_gates(self):
        """Generate QASM for U gates."""
        c = Circuit(1)
        c.u(0, 0.5, 0.3, 0.2)

        qasm = dumps(c)
        assert "u3(0.5,0.3,0.2) q[0];" in qasm

    def test_dumps_barrier(self):
        """Generate QASM with barrier."""
        c = Circuit(3)
        c.h(0)
        c.barrier([0, 1, 2])
        c.x(1)

        qasm = dumps(c)
        assert "barrier q[0],q[1],q[2];" in qasm

    def test_dumps_measurement(self):
        """Generate QASM with measurement."""
        c = Circuit(2)
        c.h(0)
        c.measure(0)
        c.measure(1)

        qasm = dumps(c)
        # Note: measurement without conditional is commented out
        # Only measurements for qubits used in conditional operations are output
        assert "// measure q[0] -> c0[0];" in qasm or "measure q[0] -> c0[0];" in qasm
        assert "// measure q[1] -> c1[0];" in qasm or "measure q[1] -> c1[0];" in qasm

    def test_dumps_reset(self):
        """Generate QASM with reset."""
        c = Circuit(2)
        c.x(0)
        c.reset(0)
        c.reset(1)

        qasm = dumps(c)
        lines = [
            line.strip() for line in qasm.split("\n") if line.strip().endswith(";")
        ]

        reset_lines = [line for line in lines if line.startswith("reset ")]
        assert reset_lines == ["reset q[0];", "reset q[1];"]

    def test_dumps_symbolic_parameters(self):
        """Generate QASM with symbolic parameters."""
        theta = Parameter("theta")
        phi = Parameter("phi")

        c = Circuit(1)
        c.rx(0, theta)
        c.ry(0, phi)

        qasm = dumps(c)
        assert "rx(theta) q[0];" in qasm
        assert "ry(phi) q[0];" in qasm

    def test_dumps_parameter_expressions(self):
        """Generate QASM with parameter expressions."""
        theta = Parameter("theta")

        c = Circuit(1)
        c.rx(0, theta + 0.5)
        c.ry(0, theta * 2)

        qasm = dumps(c)
        assert "rx(0.5 + theta) q[0];" in qasm
        assert "ry(2*theta) q[0];" in qasm


class TestQasm2DumpExtendedGates:
    """Test QASM2 dump for extended gates with definitions."""

    def test_dumps_crx(self):
        """Generate QASM for CRX with gate definition."""
        c = Circuit(2)
        c.crx(0, 1, 1.0)

        qasm = dumps(c)
        # Should include gate definition
        assert "gate crx(theta) a,b" in qasm
        # Should include usage
        assert "crx(1) q[0],q[1];" in qasm

    def test_dumps_cry(self):
        """Generate QASM for CRY with gate definition."""
        c = Circuit(2)
        c.cry(0, 1, 1.0)

        qasm = dumps(c)
        assert "gate cry(theta) a,b" in qasm
        assert "cry(1) q[0],q[1];" in qasm

    def test_dumps_rzz(self):
        """Generate QASM for RZZ with gate definition."""
        c = Circuit(2)
        c.rzz(0, 1, 0.5)

        qasm = dumps(c)
        assert "gate rzz(theta) a,b" in qasm
        assert "rzz(0.5) q[0],q[1];" in qasm

    def test_dumps_rxx(self):
        """Generate QASM for RXX with gate definition."""
        c = Circuit(2)
        c.rxx(0, 1, 0.5)

        qasm = dumps(c)
        assert "gate rxx(theta) a,b" in qasm
        assert "rxx(0.5) q[0],q[1];" in qasm

    def test_dumps_ryy(self):
        """Generate QASM for RYY with gate definition."""
        c = Circuit(2)
        c.ryy(0, 1, 0.5)

        qasm = dumps(c)
        assert "gate ryy(theta) a,b" in qasm
        assert "ryy(0.5) q[0],q[1];" in qasm

    def test_dumps_rzx(self):
        """Generate QASM for RZX with gate definition."""
        c = Circuit(2)
        c.rzx(0, 1, 0.5)

        qasm = dumps(c)
        assert "gate rzx(theta) a,b" in qasm
        assert "rzx(0.5) q[0],q[1];" in qasm


class TestQasm2DumpCustomGates:
    """Test QASM2 dump for custom gates (CircuitGate)."""

    def test_dumps_simple_custom_gate(self):
        """Generate QASM for a simple custom gate."""
        # Define sub-circuit
        sub = Circuit(2)
        sub.h(0)
        sub.cx(0, 1)
        bell = sub.to_gate("bell")

        # Use in main circuit
        c = Circuit(2)
        c.circuit_gate(bell, [0, 1])

        qasm = dumps(c)
        # Should include gate definition
        assert "gate bell q0,q1 {" in qasm
        assert "h q0;" in qasm
        assert "cx q0,q1;" in qasm
        assert "}" in qasm
        # Should include usage
        assert "bell q[0],q[1];" in qasm

    def test_dumps_parameterized_custom_gate(self):
        """Generate QASM for a parameterized custom gate."""
        theta = Parameter("theta")

        # Define sub-circuit with parameter
        sub = Circuit(1)
        sub.rx(0, theta)
        my_rx = sub.to_gate("my_rx")

        # Use with fixed value
        c = Circuit(1)
        c.circuit_gate(my_rx, [0])

        qasm = dumps(c)
        assert "gate my_rx(theta) q0 {" in qasm
        assert "rx(theta) q0;" in qasm


class TestQasm2DumpFileIO:
    """Test QASM2 file output operations."""

    def test_dump_to_file(self):
        """Save circuit to QASM file and verify content."""
        c = Circuit(2)
        c.h(0)
        c.cx(0, 1)

        with tempfile.NamedTemporaryFile(mode="w", suffix=".qasm", delete=False) as f:
            temp_path = f.name

        try:
            dump(c, temp_path)

            # Read and verify content
            with open(temp_path, "r") as f:
                content = f.read()

            assert content.startswith("// This file is auto-generated by Cqlib.")
            assert "OPENQASM 2.0;" in content
            assert "h q[0];" in content
            assert "cx q[0],q[1];" in content
        finally:
            os.unlink(temp_path)

    def test_dump_creates_valid_qasm(self):
        """Verify dumped file can be parsed back."""
        from cqlib.ir.qasm2 import load

        c1 = Circuit(3)
        c1.h(0)
        c1.cx(0, 1)
        c1.cx(0, 2)

        with tempfile.NamedTemporaryFile(mode="w", suffix=".qasm", delete=False) as f:
            temp_path = f.name

        try:
            dump(c1, temp_path)
            c2 = load(temp_path)

            assert c2.num_qubits == 3
            assert len(c2) == 3
        finally:
            os.unlink(temp_path)
