# This code is part of Cqlib.
#
# (C) Copyright China Telecom Quantum Group 2026
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

import pytest
import numpy as np
from cqlib import Circuit
from cqlib.qis import PauliString
from cqlib.ir.qasm2 import dumps


def test_pauli_evolution_single_qubit():
    circuit = Circuit(1)
    pauli = PauliString.from_str("X")
    angle = np.pi

    # Evolution: exp(-i * (pi/2) * X) = cos(pi/2) I - i sin(pi/2) X = -i X
    circuit.pauli_evolution(pauli, angle, [0])

    # Verify via unitary matrix
    mat = circuit.to_matrix()
    expected_mat = np.array([[0, -1j], [-1j, 0]], dtype=complex)

    np.testing.assert_allclose(mat, expected_mat, atol=1e-10)


def test_pauli_evolution_two_qubit_circuit_structure():
    circuit = Circuit(2)
    pauli = PauliString.from_str("ZZ")
    angle = np.pi / 2

    # Evolution: exp(-i * (pi/4) * ZZ)
    circuit.pauli_evolution(pauli, angle, [0, 1])

    qasm_str = dumps(circuit)

    # Exact structure check
    expected_qasm = (
        "// This file is auto-generated by Cqlib.\n"
        "OPENQASM 2.0;\n"
        'include "qelib1.inc";\n\n'
        "qreg q[2];\n\n\n\n"
        "cx q[0],q[1];\n"
        "rz(1.5707963267948966) q[1];\n"
        "cx q[0],q[1];\n"
    )

    assert qasm_str == expected_qasm


def test_pauli_evolution_two_qubit():
    circuit = Circuit(2)
    pauli = PauliString.from_str("ZZ")
    angle = np.pi / 2

    # Evolution: exp(-i * (pi/4) * ZZ)
    # ZZ = diag(1, -1, -1, 1)
    # exp = diag(e^{-i pi/4}, e^{i pi/4}, e^{i pi/4}, e^{-i pi/4})
    circuit.pauli_evolution(pauli, angle, [0, 1])

    mat = circuit.to_matrix()

    phase_minus = np.exp(-1j * np.pi / 4)
    phase_plus = np.exp(1j * np.pi / 4)

    expected_mat = np.diag([phase_minus, phase_plus, phase_plus, phase_minus])

    np.testing.assert_allclose(mat, expected_mat, atol=1e-10)


def test_pauli_evolution_invalid_phase():
    circuit = Circuit(1)
    # PauliString with phase other than +/- 1
    # Note: PauliString.from_str defaults to phase +1. We can create one with phase -i or something if supported.
    # Alternatively, just ensure the length mismatch raises ValueError
    pauli = PauliString.from_str("XX")

    with pytest.raises(ValueError, match="Qubit count mismatch"):
        # Mismatched qubits length (2-qubit pauli on 1 qubit)
        circuit.pauli_evolution(pauli, 1.0, [0])
