// This code is part of Cqlib.
//
// (C) Copyright China Telecom Quantum Group 2026
//
// This code is licensed under the Apache License, Version 2.0. You may
// obtain a copy of this license in the LICENSE.txt file in the root directory
// of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
//
// Any modifications or derivative works of this code must retain this
// copyright notice, and modified files need to carry a notice indicating
// that they have been altered from the originals.

use crate::circuit::gate::circuit_gate::{CircuitGate, FrozenCircuit};
use crate::circuit::gate::control_flow::ControlFlow;
use crate::circuit::gate::{Directive, Instruction, StandardGate};
use crate::circuit::operation::Operation;
use crate::circuit::param::CircuitParam;
use crate::circuit::parameter::Parameter;
use crate::circuit::{Circuit, Qubit};
use indexmap::IndexMap;
use std::collections::{HashMap, HashSet};
use std::fmt::Write;
use std::fs::File;
use std::io::{self, Write as IoWrite};
use std::path::Path;
use std::sync::Arc;

/// Errors that can occur during OpenQASM dumping
#[derive(Debug, Clone, PartialEq)]
pub enum QasmDumpError {
    /// IO error during file writing
    IoError(String),
    /// Format error during string generation
    FormatError(String),
    /// While loops are not supported in OpenQASM 2.0
    WhileLoopNotSupported,
    /// Measure inside gate definition is not allowed
    MeasureInGateNotAllowed,
    /// Invalid qubit index
    InvalidQubitIndex(String),
    /// Nested control flow is not supported
    NestedControlFlowNotSupported,
}

impl std::fmt::Display for QasmDumpError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            QasmDumpError::IoError(s) => write!(f, "IO error: {}", s),
            QasmDumpError::FormatError(s) => write!(f, "Format error: {}", s),
            QasmDumpError::WhileLoopNotSupported => {
                write!(f, "While loops are not supported in OpenQASM 2.0")
            }
            QasmDumpError::MeasureInGateNotAllowed => {
                write!(f, "Measure inside gate definition is not allowed")
            }
            QasmDumpError::InvalidQubitIndex(s) => write!(f, "Invalid qubit index: {}", s),
            QasmDumpError::NestedControlFlowNotSupported => {
                write!(f, "Nested control flow is not supported")
            }
        }
    }
}

impl std::error::Error for QasmDumpError {}

impl From<std::fmt::Error> for QasmDumpError {
    fn from(e: std::fmt::Error) -> Self {
        QasmDumpError::FormatError(e.to_string())
    }
}

impl From<io::Error> for QasmDumpError {
    fn from(e: io::Error) -> Self {
        QasmDumpError::IoError(e.to_string())
    }
}

/// Dumps a circuit to a file in OpenQASM 2.0 format.
pub fn dump<P: AsRef<Path>>(circuit: &Circuit, path: P) -> Result<(), QasmDumpError> {
    let qasm = dumps(circuit)?;
    let mut file = File::create(path)?;
    file.write_all(qasm.as_bytes())?;
    Ok(())
}

/// Dumps a circuit to a string in OpenQASM 2.0 format.
pub fn dumps(circuit: &Circuit) -> Result<String, QasmDumpError> {
    let mut output = String::new();
    writeln!(&mut output, "// This file is auto-generated by Cqlib.")?;
    writeln!(&mut output, "OPENQASM 2.0;")?;
    writeln!(&mut output, "include \"qelib1.inc\";\n")?;
    writeln!(&mut output, "qreg q[{}];", circuit.num_qubits())?;

    // Collect all qubits used in control flow conditions
    let mut conditional_qubits: HashSet<usize> = HashSet::new();
    collect_conditional_qubits(circuit, &mut conditional_qubits);

    // For OpenQASM 2.0 compliance, create single-bit registers for conditional qubits
    // Each conditional qubit gets its own register named c{idx} with size 1
    for idx in 0..circuit.num_qubits() {
        if conditional_qubits.contains(&(idx)) {
            writeln!(&mut output, "creg c{}[1];", idx)?;
        }
    }
    writeln!(&mut output)?;

    // Output global phase as a comment (OpenQASM 2.0 does not have a standard directive for this)
    let global_phase = circuit.global_phase();
    // Simple check if it's non-zero (approx)
    match global_phase.evaluate(&None) {
        Ok(val) if val.abs() < 1e-10 => {} // Zero, ignore
        Ok(val) => writeln!(&mut output, "// Global Phase: {}\n", val)?,
        Err(_) => writeln!(&mut output, "// Global Phase: {}\n", global_phase)?,
    }

    writeln!(&mut output)?;

    // Pass 0: Collect and output used extended standard gate definitions
    let mut used_standard_gates = HashSet::new();
    collect_used_standard_gates(circuit, &mut used_standard_gates);

    let extended_gates = [
        StandardGate::CRX,
        StandardGate::CRY,
        StandardGate::RZZ,
        StandardGate::RXX,
        StandardGate::RYY,
        StandardGate::RZX,
    ];

    for gate in extended_gates {
        if used_standard_gates.contains(&gate) {
            if let Some(def) = get_extended_gate_definition(gate) {
                writeln!(&mut output, "{}", def)?;
            }
        }
    }
    writeln!(&mut output)?;

    // Pass 1: Collect gate definitions (Dependencies first)
    let mut defined_gates: IndexMap<String, CircuitGate> = IndexMap::new();
    let mut unitary_gate_defs: IndexMap<String, Arc<FrozenCircuit>> = IndexMap::new();
    // UnitaryGate with only matrix (no circuit) - will be declared as opaque
    let mut opaque_unitary_gates: IndexMap<String, u16> = IndexMap::new();
    // Track if Delay is used
    let mut has_delay = false;
    collect_gates(
        circuit,
        &mut defined_gates,
        &mut unitary_gate_defs,
        &mut opaque_unitary_gates,
        &mut has_delay,
    );

    // Output CircuitGate definitions
    for gate in defined_gates.values() {
        dump_gate_definition(gate, &mut output)?;
        writeln!(&mut output)?;
    }

    // Output UnitaryGate definitions (with circuit)
    for (label, fc) in unitary_gate_defs.iter() {
        dump_unitary_gate_definition(label, fc, &mut output)?;
        writeln!(&mut output)?;
    }

    // Output opaque declarations for UnitaryGate without circuit
    for (label, num_qubits) in opaque_unitary_gates.iter() {
        dump_opaque_declaration(label, *num_qubits, &mut output)?;
        writeln!(&mut output)?;
    }

    // Output opaque declaration for Delay if used
    if has_delay {
        writeln!(&mut output, "opaque delay(t) q;")?;
        writeln!(&mut output)?;
    }

    // Pass 2: Main circuit
    // Map Qubit(i) -> "q[i]"
    let mut qubit_map: HashMap<Qubit, String> = HashMap::new();
    for q in circuit.qubits() {
        qubit_map.insert(q, format!("q[{}]", q.index()));
    }

    // Top-level parameter resolution is direct (Parameter objects are used as is)
    let param_map: HashMap<String, Parameter> = HashMap::new();

    process_circuit_operations(
        circuit,
        &mut output,
        &qubit_map,
        &param_map,
        &conditional_qubits,
    )?;

    Ok(output)
}

/// Collect all qubits that are used in control flow conditions (If/While)
fn collect_conditional_qubits(circuit: &Circuit, qubits: &mut HashSet<usize>) {
    for op in circuit.operations() {
        match &op.instruction {
            Instruction::ControlFlowGate(cf) => match cf {
                ControlFlow::IfElse(if_else) => {
                    qubits.insert(if_else.condition().qubit.index());
                    // Recurse into true body
                    for body_op in if_else.true_body() {
                        collect_conditional_qubits_from_op(body_op, qubits);
                    }
                    // Recurse into false body
                    if let Some(false_body) = if_else.false_body() {
                        for body_op in false_body {
                            collect_conditional_qubits_from_op(body_op, qubits);
                        }
                    }
                }
                ControlFlow::WhileLoop(while_loop) => {
                    qubits.insert(while_loop.condition().qubit.index());
                    for body_op in while_loop.body() {
                        collect_conditional_qubits_from_op(body_op, qubits);
                    }
                }
            },
            Instruction::CircuitGate(cg) => {
                collect_conditional_qubits(&cg.circuit.circuit, qubits);
            }
            Instruction::UnitaryGate(ug) => {
                if let Some(fc) = ug.circuit() {
                    collect_conditional_qubits(&fc.circuit, qubits);
                }
            }
            _ => {}
        }
    }
}

/// Helper to collect conditional qubits from a single operation
fn collect_conditional_qubits_from_op(op: &Operation, qubits: &mut HashSet<usize>) {
    if let Instruction::ControlFlowGate(cf) = &op.instruction {
        match cf {
            ControlFlow::IfElse(if_else) => {
                qubits.insert(if_else.condition().qubit.index());
            }
            ControlFlow::WhileLoop(while_loop) => {
                qubits.insert(while_loop.condition().qubit.index());
            }
        }
    }
}

fn collect_gates(
    circuit: &Circuit,
    defined_gates: &mut IndexMap<String, CircuitGate>,
    unitary_gate_defs: &mut IndexMap<String, Arc<FrozenCircuit>>,
    opaque_unitary_gates: &mut IndexMap<String, u16>,
    has_delay: &mut bool,
) {
    for op in circuit.operations() {
        match &op.instruction {
            Instruction::CircuitGate(cg) => {
                // Recurse first (Post-order traversal ensures dependencies are collected first)
                collect_gates(
                    &cg.circuit.circuit,
                    defined_gates,
                    unitary_gate_defs,
                    opaque_unitary_gates,
                    has_delay,
                );

                if let Some(existing) = defined_gates.get(cg.name.as_str()) {
                    // Basic collision detection: Check if interface matches
                    if existing.num_qubits() != cg.num_qubits()
                        || existing.num_params() != cg.num_params()
                    {
                        eprintln!(
                            "Warning: Gate name collision detected for '{}'. Existing: (q={}, p={}), New: (q={}, p={}). The existing definition will be used.",
                            cg.name,
                            existing.num_qubits(),
                            existing.num_params(),
                            cg.num_qubits(),
                            cg.num_params()
                        );
                    }
                    // Deep structural comparison is expensive and requires PartialEq on Circuit, skipping for now.
                } else {
                    defined_gates.insert(cg.name.to_string(), *cg.clone());
                }
            }
            Instruction::UnitaryGate(ug) => {
                if let Some(fc) = ug.circuit() {
                    // Recurse into UnitaryGate's internal circuit first
                    collect_gates(
                        &fc.circuit,
                        defined_gates,
                        unitary_gate_defs,
                        opaque_unitary_gates,
                        has_delay,
                    );

                    // Register this UnitaryGate as a gate definition
                    let label = ug.label().to_string();
                    if !unitary_gate_defs.contains_key(&label) {
                        unitary_gate_defs.insert(label, fc.clone());
                    }
                } else {
                    // UnitaryGate without circuit (only matrix) - will be declared as opaque
                    let label = ug.label().to_string();
                    if !opaque_unitary_gates.contains_key(&label) {
                        opaque_unitary_gates.insert(label, ug.num_qubits());
                    }
                }
            }
            Instruction::Delay => {
                *has_delay = true;
            }
            _ => {}
        }
    }
}

fn dump_gate_definition(cg: &CircuitGate, output: &mut String) -> Result<(), QasmDumpError> {
    let params: Vec<String> = cg.symbols().iter().cloned().collect();
    let params_str = if params.is_empty() {
        String::new()
    } else {
        format!("({})", params.join(","))
    };

    let qubits: Vec<String> = (0..cg.num_qubits()).map(|i| format!("q{}", i)).collect();
    let qubits_str = qubits.join(",");

    writeln!(output, "gate {}{} {} {{", cg.name, params_str, qubits_str)?;

    // Body context
    // Map inner qubits to formal parameters: Qubit(i) -> "qi"
    let mut body_qubit_map = HashMap::new();
    let inner_circuit = &cg.circuit.circuit;
    // We assume the inner circuit qubits are ordered 0..N corresponding to arguments
    // Or we use the order in `inner_circuit.qubits()`
    for (i, q) in inner_circuit.qubits().iter().enumerate() {
        body_qubit_map.insert(*q, format!("q{}", i));
    }

    // Parameters in body are symbols, which match the formal parameters in name.
    // No substitution needed.
    let body_param_map = HashMap::new();

    // For gate definitions, we don't have conditional qubits (gates can't contain control flow)
    let empty_conditional_qubits: HashSet<usize> = HashSet::new();
    process_circuit_operations(
        inner_circuit,
        output,
        &body_qubit_map,
        &body_param_map,
        &empty_conditional_qubits,
    )?;

    writeln!(output, "}}")?;
    Ok(())
}

fn dump_unitary_gate_definition(
    label: &str,
    frozen_circuit: &FrozenCircuit,
    output: &mut String,
) -> Result<(), QasmDumpError> {
    let num_qubits = frozen_circuit.circuit.qubits().len();
    let qubits: Vec<String> = (0..num_qubits).map(|i| format!("q{}", i)).collect();
    let qubits_str = qubits.join(",");

    writeln!(output, "gate {} {} {{", label, qubits_str)?;

    // Body context
    let mut body_qubit_map = HashMap::new();
    let inner_circuit = &frozen_circuit.circuit;
    for (i, q) in inner_circuit.qubits().iter().enumerate() {
        body_qubit_map.insert(*q, format!("q{}", i));
    }

    let body_param_map = HashMap::new();
    // For gate definitions, we don't have conditional qubits (gates can't contain control flow)
    let empty_conditional_qubits: HashSet<usize> = HashSet::new();
    process_circuit_operations(
        inner_circuit,
        output,
        &body_qubit_map,
        &body_param_map,
        &empty_conditional_qubits,
    )?;

    writeln!(output, "}}")?;
    Ok(())
}

fn dump_opaque_declaration(
    label: &str,
    num_qubits: u16,
    output: &mut String,
) -> Result<(), QasmDumpError> {
    let qubits: Vec<String> = (0..num_qubits).map(|i| format!("q{}", i)).collect();
    let qubits_str = qubits.join(",");

    writeln!(output, "opaque {} {};", label, qubits_str)?;
    Ok(())
}

fn process_circuit_operations(
    circuit: &Circuit,
    output: &mut String,
    qubit_map: &HashMap<Qubit, String>,
    param_map: &HashMap<String, Parameter>,
    conditional_qubits: &HashSet<usize>,
) -> Result<(), QasmDumpError> {
    for op in circuit.operations() {
        match &op.instruction {
            Instruction::Standard(gate) => {
                dump_standard_gate(gate, op, circuit, output, qubit_map, param_map)?;
            }
            Instruction::McGate(mc_gate) => {
                dump_mc_gate(mc_gate, op, circuit, output, qubit_map, param_map)?;
            }
            Instruction::Directive(directive) => {
                dump_directive(directive, op, output, qubit_map, conditional_qubits)?;
            }
            Instruction::CircuitGate(cg) => {
                // Output gate call: name(params) qubits;

                // Resolve arguments
                let params_str = format_params(op, circuit, param_map);

                // Map qubits
                let mapped_qs = map_qubits(op, qubit_map);

                writeln!(output, "{}{} {};", cg.name, params_str, mapped_qs.join(","))?;
            }
            Instruction::UnitaryGate(unitary_gate) => {
                // Output gate call: label qubits;
                // (The gate definition or opaque declaration was already output in Pass 1)
                let mapped_qs = map_qubits(op, qubit_map);
                writeln!(output, "{} {};", unitary_gate.label(), mapped_qs.join(","))?;
            }
            Instruction::ControlFlowGate(gate) => {
                dump_control_flow(
                    gate,
                    op,
                    circuit,
                    output,
                    qubit_map,
                    param_map,
                    conditional_qubits,
                )?;
            }
            Instruction::Delay => {
                // Output delay gate call: delay(value) q[i];
                let params_str = format_params(op, circuit, param_map);
                let mapped_qs = map_qubits(op, qubit_map);

                writeln!(output, "delay({}) {};", params_str, mapped_qs[0])?;
            }
        }
    }
    Ok(())
}

fn resolve_param(
    circuit_param: &CircuitParam,
    circuit: &Circuit,
    param_map: &HashMap<String, Parameter>,
) -> Parameter {
    let mut param = match circuit_param {
        CircuitParam::Fixed(val) => Parameter::from(*val),
        CircuitParam::Index(idx) => circuit.parameters()[*idx as usize].clone(),
    };

    if !param_map.is_empty() {
        for (sym, repl) in param_map {
            param = param.replace(sym, repl);
        }
    }

    param = param.simplify(None);
    param
}

fn format_params(
    op: &Operation,
    circuit: &Circuit,
    param_map: &HashMap<String, Parameter>,
) -> String {
    if op.params.is_empty() {
        return String::new();
    }
    let params_str: Vec<String> = op
        .params
        .iter()
        .map(|p| resolve_param(p, circuit, param_map).to_string())
        .collect();
    format!("({})", params_str.join(","))
}

fn map_qubits(op: &Operation, qubit_map: &HashMap<Qubit, String>) -> Vec<String> {
    op.qubits
        .iter()
        .map(|q| {
            qubit_map
                .get(q)
                .cloned()
                .unwrap_or_else(|| format!("unknown[{}]", q.index()))
        })
        .collect()
}

fn dump_standard_gate(
    gate: &StandardGate,
    op: &Operation,
    circuit: &Circuit,
    output: &mut String,
    qubit_map: &HashMap<Qubit, String>,
    param_map: &HashMap<String, Parameter>,
) -> Result<(), QasmDumpError> {
    let mapped_qs = map_qubits(op, qubit_map);

    match gate {
        StandardGate::X2P => {
            writeln!(output, "// x2p {}", mapped_qs[0])?;
            writeln!(output, "rx(pi/2) {}", mapped_qs[0])?;
            return Ok(());
        }
        StandardGate::X2M => {
            writeln!(output, "// x2m {}", mapped_qs[0])?;
            writeln!(output, "rx(-pi/2) {}", mapped_qs[0])?;
            return Ok(());
        }
        StandardGate::Y2P => {
            writeln!(output, "// y2p {}", mapped_qs[0])?;
            writeln!(output, "ry(pi/2) {}", mapped_qs[0])?;
            return Ok(());
        }
        StandardGate::Y2M => {
            writeln!(output, "// y2m {}", mapped_qs[0])?;
            writeln!(output, "ry(-pi/2) {}", mapped_qs[0])?;
            return Ok(());
        }
        StandardGate::XY2P => {
            let theta = resolve_param(&op.params[0], circuit, param_map);
            let p1 = Parameter::pi() / 2.0 - theta.clone();
            let p3 = theta.clone() - Parameter::pi() / 2.0;
            let q_str = &mapped_qs[0];

            writeln!(output, "// xy2p({}) {}", theta, q_str)?;
            writeln!(output, "rz({}) {}", p1, q_str)?;
            writeln!(output, "ry(pi/2) {}", q_str)?;
            writeln!(output, "rz({}) {}", p3, q_str)?;
            return Ok(());
        }
        StandardGate::XY2M => {
            let theta = resolve_param(&op.params[0], circuit, param_map);
            let m1 = Parameter::from(0.0) - (Parameter::pi() / 2.0 + theta.clone());
            let m3 = theta.clone() + Parameter::pi() / 2.0;
            let q_str = &mapped_qs[0];

            writeln!(output, "// xy2m({}) {}", theta, q_str)?;
            writeln!(output, "rz({}) {}", m1, q_str)?;
            writeln!(output, "ry(pi/2) {}", q_str)?;
            writeln!(output, "rz({}) {}", m3, q_str)?;
            return Ok(());
        }
        StandardGate::GPhase => {
            let param = resolve_param(&op.params[0], circuit, param_map);
            writeln!(output, "// gphase({})", param)?;
            return Ok(());
        }
        _ => {}
    }

    let name = match gate {
        StandardGate::I => "id",
        StandardGate::X => "x",
        StandardGate::Y => "y",
        StandardGate::Z => "z",
        StandardGate::H => "h",
        StandardGate::S => "s",
        StandardGate::SDG => "sdg",
        StandardGate::T => "t",
        StandardGate::TDG => "tdg",
        StandardGate::RX => "rx",
        StandardGate::RY => "ry",
        StandardGate::RZ => "rz",
        StandardGate::Phase => "u1",
        StandardGate::CX => "cx",
        StandardGate::CY => "cy",
        StandardGate::CZ => "cz",
        StandardGate::SWAP => "swap",
        StandardGate::CCX => "ccx",
        StandardGate::U => "u3",
        StandardGate::CRZ => "crz",
        StandardGate::XY => "xy",
        StandardGate::FSIM => "fsim",
        StandardGate::RXY => "rxy",

        StandardGate::CRX => "crx",
        StandardGate::CRY => "cry",
        StandardGate::RXX => "rxx",
        StandardGate::RYY => "ryy",
        StandardGate::RZZ => "rzz",
        StandardGate::RZX => "rzx",

        StandardGate::X2P
        | StandardGate::X2M
        | StandardGate::Y2P
        | StandardGate::Y2M
        | StandardGate::XY2P
        | StandardGate::XY2M
        | StandardGate::GPhase => "_",
    };

    let params_str = format_params(op, circuit, param_map);
    writeln!(output, "{}{} {};", name, params_str, mapped_qs.join(","))?;
    Ok(())
}

fn dump_directive(
    directive: &Directive,
    op: &Operation,
    output: &mut String,
    qubit_map: &HashMap<Qubit, String>,
    conditional_qubits: &HashSet<usize>,
) -> Result<(), QasmDumpError> {
    let mapped_qs = map_qubits(op, qubit_map);

    match directive {
        Directive::Measure => {
            // Only output measure statement if the qubit is used in conditional operations
            // Otherwise, comment it out (no register to store the result)
            for q_str in mapped_qs {
                if q_str.starts_with("q[") && q_str.ends_with("]") {
                    let idx_str = &q_str[2..q_str.len() - 1];
                    if let Ok(idx) = idx_str.parse::<usize>() {
                        if conditional_qubits.contains(&idx) {
                            // Qubit is used in condition - output actual measure to its register
                            writeln!(output, "measure {} -> c{}[0];", q_str, idx)?;
                        } else {
                            // No condition uses this qubit - comment out the measure
                            writeln!(output, "// measure {} -> c{}[0];", q_str, idx)?;
                        }
                    } else {
                        return Err(QasmDumpError::InvalidQubitIndex(q_str.to_string()));
                    }
                } else {
                    // Inside gate or non-standard naming.
                    return Err(QasmDumpError::MeasureInGateNotAllowed);
                }
            }
        }
        Directive::Barrier => {
            writeln!(output, "barrier {};", mapped_qs.join(","))?;
        }
        Directive::Reset => {
            for q in mapped_qs {
                writeln!(output, "reset {};", q)?;
            }
        }
    }
    Ok(())
}

fn dump_mc_gate(
    mc_gate: &crate::circuit::gate::MCGate,
    op: &Operation,
    circuit: &Circuit,
    output: &mut String,
    qubit_map: &HashMap<Qubit, String>,
    param_map: &HashMap<String, Parameter>,
) -> Result<(), QasmDumpError> {
    let num_ctrl = mc_gate.num_ctrl_qubits();
    let base = mc_gate.base_gate();

    let name = match (num_ctrl, base) {
        (1, StandardGate::X) => "cx",
        (1, StandardGate::Z) => "cz",
        (1, StandardGate::Y) => "cy",
        (1, StandardGate::H) => "ch",
        (1, StandardGate::RX) => "crx",
        (1, StandardGate::RY) => "cry",
        (1, StandardGate::RZ) => "crz",
        (1, StandardGate::Phase) => "cu1",
        (1, StandardGate::CX) => "ccx",
        (1, StandardGate::SWAP) => "cswap",
        (2, StandardGate::X) => "ccx",
        _ => {
            return Err(QasmDumpError::FormatError(format!(
                "Unsupported MCGate: {} controls on {}",
                num_ctrl, base
            )));
        }
    };

    let params_str = format_params(op, circuit, param_map);
    let mapped_qs = map_qubits(op, qubit_map);

    writeln!(output, "{}{} {};", name, params_str, mapped_qs.join(","))?;
    Ok(())
}

fn collect_used_standard_gates(circuit: &Circuit, used_gates: &mut HashSet<StandardGate>) {
    for op in circuit.operations() {
        match &op.instruction {
            Instruction::Standard(sg) => {
                used_gates.insert(*sg);
            }
            Instruction::CircuitGate(cg) => {
                collect_used_standard_gates(&cg.circuit.circuit, used_gates);
            }
            Instruction::UnitaryGate(ug) => {
                if let Some(fc) = ug.circuit() {
                    collect_used_standard_gates(&fc.circuit, used_gates);
                }
            }
            _ => {}
        }
    }
}

/// Dump a control flow gate (IfElse or WhileLoop) to QASM format
fn dump_control_flow(
    gate: &ControlFlow,
    _op: &Operation,
    circuit: &Circuit,
    output: &mut String,
    qubit_map: &HashMap<Qubit, String>,
    param_map: &HashMap<String, Parameter>,
    _conditional_qubits: &HashSet<usize>,
) -> Result<(), QasmDumpError> {
    match gate {
        ControlFlow::IfElse(if_else) => {
            // Get the condition qubit index - in OpenQASM 2.0, this maps to a single-bit creg
            // The register is named c{idx} (e.g., c0, c1) with size 1
            let cond_qubit_idx = if_else.condition().qubit.index();
            let target_value = if_else.condition().target;
            let creg_name = format!("c{}", cond_qubit_idx);

            // Dump true body operations
            let true_body = if_else.true_body();
            for body_op in true_body {
                let body_qasm = operation_to_qasm(body_op, circuit, qubit_map, param_map)?;
                // OpenQASM 2.0 format: if (creg == value) op;
                writeln!(
                    output,
                    "if ({} == {}) {};",
                    creg_name, target_value, body_qasm
                )?;
            }

            // Dump false body operations (else branch)
            // OpenQASM 2.0 doesn't have native else, so we use inverted condition
            if let Some(false_body) = if_else.false_body() {
                for body_op in false_body {
                    let body_qasm = operation_to_qasm(body_op, circuit, qubit_map, param_map)?;
                    // Invert condition: if (creg == 1-value) op;
                    let inverted_value = if target_value == 0 { 1 } else { 0 };
                    writeln!(
                        output,
                        "if ({} == {}) {};",
                        creg_name, inverted_value, body_qasm
                    )?;
                }
            }
        }
        ControlFlow::WhileLoop(_while_loop) => {
            // OpenQASM 2.0 does not support while loops
            return Err(QasmDumpError::WhileLoopNotSupported);
        }
    }
    Ok(())
}

/// Convert a single operation to QASM string (without semicolon)
fn operation_to_qasm(
    op: &Operation,
    circuit: &Circuit,
    qubit_map: &HashMap<Qubit, String>,
    param_map: &HashMap<String, Parameter>,
) -> Result<String, QasmDumpError> {
    match &op.instruction {
        Instruction::Standard(gate) => {
            // Use the same pattern as dump_standard_gate
            let name = match gate {
                StandardGate::I => "id",
                StandardGate::X => "x",
                StandardGate::Y => "y",
                StandardGate::Z => "z",
                StandardGate::H => "h",
                StandardGate::S => "s",
                StandardGate::SDG => "sdg",
                StandardGate::T => "t",
                StandardGate::TDG => "tdg",
                StandardGate::RX => "rx",
                StandardGate::RY => "ry",
                StandardGate::RZ => "rz",
                StandardGate::Phase => "u1",
                StandardGate::CX => "cx",
                StandardGate::CY => "cy",
                StandardGate::CZ => "cz",
                StandardGate::SWAP => "swap",
                StandardGate::CCX => "ccx",
                StandardGate::U => "u3",
                StandardGate::CRZ => "crz",
                StandardGate::XY => "xy",
                StandardGate::FSIM => "fsim",
                StandardGate::RXY => "rxy",
                StandardGate::CRX => "crx",
                StandardGate::CRY => "cry",
                StandardGate::RXX => "rxx",
                StandardGate::RYY => "ryy",
                StandardGate::RZZ => "rzz",
                StandardGate::RZX => "rzx",
                _ => "unknown",
            };
            let params_str = format_params(op, circuit, param_map);
            let mapped_qs = map_qubits(op, qubit_map);
            Ok(format!("{}{} {}", name, params_str, mapped_qs.join(",")))
        }
        Instruction::McGate(mc_gate) => {
            let num_ctrl = mc_gate.num_ctrl_qubits();
            let base = mc_gate.base_gate();
            let name = match (num_ctrl, base) {
                (1, StandardGate::X) => "cx",
                (2, StandardGate::X) => "ccx",
                (1, StandardGate::Z) => "cz",
                (1, StandardGate::Y) => "cy",
                (1, StandardGate::H) => "ch",
                (1, StandardGate::CX) => "ccx",
                (1, StandardGate::RX) => "crx",
                (1, StandardGate::RY) => "cry",
                (1, StandardGate::RZ) => "crz",
                (1, StandardGate::SWAP) => "cswap",
                (1, StandardGate::Phase) => "cu1",
                _ => {
                    return Err(QasmDumpError::FormatError(format!(
                        "Unsupported multi-controlled gate: {}-controlled {:?}",
                        num_ctrl, base
                    )));
                }
            };
            let params_str = format_params(op, circuit, param_map);
            let mapped_qs = map_qubits(op, qubit_map);
            Ok(format!("{}{} {}", name, params_str, mapped_qs.join(",")))
        }
        Instruction::Directive(directive) => match directive {
            Directive::Barrier => {
                let mapped_qs = map_qubits(op, qubit_map);
                Ok(format!("barrier {}", mapped_qs.join(",")))
            }
            Directive::Reset => {
                let mapped_qs = map_qubits(op, qubit_map);
                Ok(format!("reset {}", mapped_qs[0]))
            }
            Directive::Measure => Err(QasmDumpError::MeasureInGateNotAllowed),
        },
        Instruction::CircuitGate(cg) => {
            let params_str = format_params(op, circuit, param_map);
            let mapped_qs = map_qubits(op, qubit_map);
            Ok(format!("{}{} {}", cg.name, params_str, mapped_qs.join(",")))
        }
        Instruction::UnitaryGate(unitary_gate) => {
            let mapped_qs = map_qubits(op, qubit_map);
            Ok(format!("{} {}", unitary_gate.label(), mapped_qs.join(",")))
        }
        Instruction::ControlFlowGate(_) => Err(QasmDumpError::NestedControlFlowNotSupported),
        Instruction::Delay => {
            let params_str = format_params(op, circuit, param_map);
            let mapped_qs = map_qubits(op, qubit_map);
            Ok(format!("delay({}) {}", params_str, mapped_qs[0]))
        }
    }
}

fn get_extended_gate_definition(gate: StandardGate) -> Option<&'static str> {
    match gate {
        StandardGate::CRX => {
            Some("gate crx(theta) a,b { h b;rz(theta/2) b; cx a,b; rz(-theta/2) b; cx a,b; h b;}")
        }
        StandardGate::CRY => {
            Some("gate cry(theta) a,b { ry(theta/2) b; cx a,b; ry(-theta/2) b; cx a,b; }")
        }
        StandardGate::RZZ => Some("gate rzz(theta) a,b { cx a,b; rz(theta) b; cx a,b; }"),
        StandardGate::RXX => {
            Some("gate rxx(theta) a,b { h a; h b; cx a,b; rz(theta) b; cx a,b; h a; h b; }")
        }
        StandardGate::RYY => Some(
            "gate ryy(theta) a,b { rx(pi/2) a; rx(pi/2) b; cx a,b; rz(theta) b; cx a,b; rx(-pi/2) a; rx(-pi/2) b; }",
        ),
        StandardGate::RZX => Some("gate rzx(theta) a,b { h b; cx a,b; rz(theta) b; cx a,b; h b; }"),
        _ => None,
    }
}

#[cfg(test)]
#[path = "./dump_test.rs"]
mod dump_test;
