// This code is part of Cqlib.
//
// (C) Copyright China Telecom Quantum Group 2026
//
// This code is licensed under the Apache License, Version 2.0. You may
// obtain a copy of this license in the LICENSE.txt file in the root directory
// of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
//
// Any modifications or derivative works of this code must retain this
// copyright notice, and modified files need to carry a notice indicating
// that they have been altered from the originals.

use crate::circuit::gate::circuit_gate::CircuitGate;
use crate::circuit::gate::{Directive, Instruction, StandardGate};
use crate::circuit::operation::Operation;
use crate::circuit::param::CircuitParam;
use crate::circuit::parameter::Parameter;
use crate::circuit::{Circuit, Qubit};
use indexmap::IndexMap;
use std::collections::HashMap;
use std::fmt::Write;
use std::fs::File;
use std::io::{self, Write as IoWrite};
use std::path::Path;

/// Dumps a circuit to a file in OpenQASM 2.0 format.
pub fn dump<P: AsRef<Path>>(circuit: &Circuit, path: P) -> io::Result<()> {
    let qasm = dumps(circuit).map_err(io::Error::other)?;
    let mut file = File::create(path)?;
    file.write_all(qasm.as_bytes())?;
    Ok(())
}

/// Dumps a circuit to a string in OpenQASM 2.0 format.
pub fn dumps(circuit: &Circuit) -> Result<String, std::fmt::Error> {
    let mut output = String::new();
    writeln!(&mut output, "// This file is auto-generated by Cqlib.")?;
    writeln!(&mut output, "OPENQASM 2.0;")?;
    writeln!(&mut output, "include \"qelib1.inc\";\n")?;
    writeln!(&mut output, "qreg q[{}];", circuit.num_qubits())?;

    // Check if we need a classical register (if there are measurements)
    // For simplicity, we always create a matching classical register "c"
    // to support the default "measure q -> c" behavior.
    writeln!(&mut output, "creg c[{}];\n", circuit.num_qubits())?;

    // Output global phase as a comment (OpenQASM 2.0 does not have a standard directive for this)
    let global_phase = circuit.global_phase();
    // Simple check if it's non-zero (approx)
    match global_phase.evaluate(&None) {
        Ok(val) if val.abs() < 1e-10 => {} // Zero, ignore
        Ok(val) => writeln!(&mut output, "// Global Phase: {}\n", val)?,
        Err(_) => writeln!(&mut output, "// Global Phase: {}\n", global_phase)?,
    }

    writeln!(&mut output)?;

    // Pass 1: Collect gate definitions (Dependencies first)
    let mut defined_gates: IndexMap<String, CircuitGate> = IndexMap::new();
    collect_gates(circuit, &mut defined_gates);

    // Output gate definitions
    for gate in defined_gates.values() {
        dump_gate_definition(gate, &mut output)?;
        writeln!(&mut output)?;
    }

    // Pass 2: Main circuit
    // Map Qubit(i) -> "q[i]"
    let mut qubit_map: HashMap<Qubit, String> = HashMap::new();
    for q in circuit.qubits() {
        qubit_map.insert(q, format!("q[{}]", q.index()));
    }

    // Top-level parameter resolution is direct (Parameter objects are used as is)
    let param_map: HashMap<String, Parameter> = HashMap::new();

    process_circuit_operations(circuit, &mut output, &qubit_map, &param_map)?;

    Ok(output)
}

fn collect_gates(circuit: &Circuit, defined_gates: &mut IndexMap<String, CircuitGate>) {
    for op in circuit.operations() {
        if let Instruction::CircuitGate(cg) = &op.instruction {
            // Recurse first (Post-order traversal ensures dependencies are collected first)
            collect_gates(&cg.circuit.circuit, defined_gates);

            if let Some(existing) = defined_gates.get(cg.name.as_str()) {
                // Basic collision detection: Check if interface matches
                if existing.num_qubits() != cg.num_qubits()
                    || existing.num_params() != cg.num_params()
                {
                    eprintln!(
                        "Warning: Gate name collision detected for '{}'. Existing: (q={}, p={}), New: (q={}, p={}). The existing definition will be used.",
                        cg.name,
                        existing.num_qubits(),
                        existing.num_params(),
                        cg.num_qubits(),
                        cg.num_params()
                    );
                }
                // Deep structural comparison is expensive and requires PartialEq on Circuit, skipping for now.
            } else {
                defined_gates.insert(cg.name.to_string(), *cg.clone());
            }
        }
    }
}

fn dump_gate_definition(cg: &CircuitGate, output: &mut String) -> std::fmt::Result {
    let params: Vec<String> = cg.symbols().iter().cloned().collect();
    let params_str = if params.is_empty() {
        String::new()
    } else {
        format!("({})", params.join(","))
    };

    let qubits: Vec<String> = (0..cg.num_qubits()).map(|i| format!("q{}", i)).collect();
    let qubits_str = qubits.join(",");

    writeln!(output, "gate {}{} {} {{", cg.name, params_str, qubits_str)?;

    // Body context
    // Map inner qubits to formal parameters: Qubit(i) -> "qi"
    let mut body_qubit_map = HashMap::new();
    let inner_circuit = &cg.circuit.circuit;
    // We assume the inner circuit qubits are ordered 0..N corresponding to arguments
    // Or we use the order in `inner_circuit.qubits()`
    for (i, q) in inner_circuit.qubits().iter().enumerate() {
        body_qubit_map.insert(*q, format!("q{}", i));
    }

    // Parameters in body are symbols, which match the formal parameters in name.
    // No substitution needed.
    let body_param_map = HashMap::new();

    process_circuit_operations(inner_circuit, output, &body_qubit_map, &body_param_map)?;

    writeln!(output, "}}")
}

fn process_circuit_operations(
    circuit: &Circuit,
    output: &mut String,
    qubit_map: &HashMap<Qubit, String>,
    param_map: &HashMap<String, Parameter>,
) -> std::fmt::Result {
    for op in circuit.operations() {
        match &op.instruction {
            Instruction::Standard(gate) => {
                dump_standard_gate(gate, op, circuit, output, qubit_map, param_map)?;
            }
            Instruction::McGate(mc_gate) => {
                dump_mc_gate(mc_gate, op, circuit, output, qubit_map, param_map)?;
            }
            Instruction::Directive(directive) => {
                dump_directive(directive, op, output, qubit_map)?;
            }
            Instruction::CircuitGate(cg) => {
                // Output gate call: name(params) qubits;

                // Resolve arguments
                let params_str = format_params(op, circuit, param_map);

                // Map qubits
                let mapped_qs = map_qubits(op, qubit_map);

                writeln!(output, "{}{} {};", cg.name, params_str, mapped_qs.join(","))?;
            }
            Instruction::UnitaryGate(_) => {
                writeln!(
                    output,
                    "// UnitaryGate: Custom matrix operations not fully supported in QASM 2.0 dump"
                )?;
            }
            Instruction::Delay => {
                let params_str = format_params(op, circuit, param_map);
                let mapped_qs = map_qubits(op, qubit_map);

                writeln!(
                    output,
                    "Delay({}dt) {:?}; // DelayGate: Native delay not supported in QASM 2.0",
                    params_str, mapped_qs[0]
                )?;
            }
        }
    }
    Ok(())
}

fn resolve_param(
    circuit_param: &CircuitParam,
    circuit: &Circuit,
    param_map: &HashMap<String, Parameter>,
) -> Parameter {
    let mut param = match circuit_param {
        CircuitParam::Fixed(val) => Parameter::from(*val),
        CircuitParam::Index(idx) => circuit.parameters()[*idx as usize].clone(),
    };

    if !param_map.is_empty() {
        for (sym, repl) in param_map {
            param = param.replace(sym, repl);
        }
    }

    param = param.simplify(None);
    param
}

fn format_params(
    op: &Operation,
    circuit: &Circuit,
    param_map: &HashMap<String, Parameter>,
) -> String {
    if op.params.is_empty() {
        return String::new();
    }
    let params_str: Vec<String> = op
        .params
        .iter()
        .map(|p| resolve_param(p, circuit, param_map).to_string())
        .collect();
    format!("({})", params_str.join(","))
}

fn map_qubits(op: &Operation, qubit_map: &HashMap<Qubit, String>) -> Vec<String> {
    op.qubits
        .iter()
        .map(|q| {
            qubit_map
                .get(q)
                .cloned()
                .unwrap_or_else(|| format!("unknown[{}]", q.index()))
        })
        .collect()
}

fn dump_standard_gate(
    gate: &StandardGate,
    op: &Operation,
    circuit: &Circuit,
    output: &mut String,
    qubit_map: &HashMap<Qubit, String>,
    param_map: &HashMap<String, Parameter>,
) -> std::fmt::Result {
    let mapped_qs = map_qubits(op, qubit_map);

    match gate {
        StandardGate::X2P => {
            return writeln!(output, "rx(pi/2) {}", mapped_qs[0]);
        }
        StandardGate::X2M => {
            return writeln!(output, "rx(-pi/2) {}", mapped_qs[0]);
        }
        StandardGate::Y2P => {
            return writeln!(output, "ry(pi/2) {}", mapped_qs[0]);
        }
        StandardGate::Y2M => {
            return writeln!(output, "ry(-pi/2) {}", mapped_qs[0]);
        }
        StandardGate::XY2P => {
            let theta = resolve_param(&op.params[0], circuit, param_map);
            let p1 = Parameter::pi() / 2.0 - theta.clone();
            let p3 = theta.clone() - Parameter::pi() / 2.0;
            let q_str = &mapped_qs[0];

            writeln!(output, "rz({}) {}", p1, q_str)?;
            writeln!(output, "ry(pi/2) {}", q_str)?;
            return writeln!(output, "rz({}) {}", p3, q_str);
        }
        StandardGate::XY2M => {
            let theta = resolve_param(&op.params[0], circuit, param_map);
            let m1 = Parameter::from(0.0) - (Parameter::pi() / 2.0 + theta.clone());
            let m3 = theta.clone() + Parameter::pi() / 2.0;
            let q_str = &mapped_qs[0];

            writeln!(output, "rz({}) {}", m1, q_str)?;
            writeln!(output, "ry(pi/2) {}", q_str)?;
            return writeln!(output, "rz({}) {}", m3, q_str);
        }
        StandardGate::GPhase => {
            let param = resolve_param(&op.params[0], circuit, param_map);
            return writeln!(output, "// gphase({})", param);
        }
        _ => {}
    }

    let name = match gate {
        StandardGate::I => "id",
        StandardGate::X => "x",
        StandardGate::Y => "y",
        StandardGate::Z => "z",
        StandardGate::H => "h",
        StandardGate::S => "s",
        StandardGate::SDG => "sdg",
        StandardGate::T => "t",
        StandardGate::TDG => "tdg",
        StandardGate::RX => "rx",
        StandardGate::RY => "ry",
        StandardGate::RZ => "rz",
        StandardGate::Phase => "u1",
        StandardGate::CX => "cx",
        StandardGate::CY => "cy",
        StandardGate::CZ => "cz",
        StandardGate::SWAP => "swap",
        StandardGate::CCX => "ccx",
        StandardGate::U => "u3",
        StandardGate::RXX => "rxx",
        StandardGate::RYY => "ryy",
        StandardGate::RZZ => "rzz",
        StandardGate::RZX => "rzx",
        StandardGate::CRX => "crx",
        StandardGate::CRY => "cry",
        StandardGate::CRZ => "crz",
        StandardGate::XY => "xy",
        StandardGate::FSIM => "fsim",
        StandardGate::RXY => "rxy",

        StandardGate::X2P => "_",
        StandardGate::X2M => "_",
        StandardGate::Y2P => "_",
        StandardGate::Y2M => "_",
        StandardGate::XY2P => "_",
        StandardGate::XY2M => "_",
        StandardGate::GPhase => "_",
    };

    let params_str = format_params(op, circuit, param_map);
    writeln!(output, "{}{} {};", name, params_str, mapped_qs.join(","))
}

fn dump_directive(
    directive: &Directive,
    op: &Operation,
    output: &mut String,
    qubit_map: &HashMap<Qubit, String>,
) -> std::fmt::Result {
    let mapped_qs = map_qubits(op, qubit_map);

    match directive {
        Directive::Measure => {
            // Measure q[i] -> c[i]
            for q_str in mapped_qs {
                if q_str.starts_with("q[") && q_str.ends_with("]") {
                    let idx_str = &q_str[2..q_str.len() - 1];
                    writeln!(output, "measure {} -> c[{}];", q_str, idx_str)?;
                } else {
                    // Inside gate or non-standard naming.
                    writeln!(
                        output,
                        "// measure {}; // Warning: Measure inside gate or unknown register",
                        q_str
                    )?;
                }
            }
        }
        Directive::Barrier => {
            writeln!(output, "barrier {};", mapped_qs.join(","))?;
        }
        Directive::Reset => {
            for q in mapped_qs {
                writeln!(output, "reset {};", q)?;
            }
        }
    }
    Ok(())
}

fn dump_mc_gate(
    mc_gate: &crate::circuit::gate::MCGate,
    op: &Operation,
    circuit: &Circuit,
    output: &mut String,
    qubit_map: &HashMap<Qubit, String>,
    param_map: &HashMap<String, Parameter>,
) -> std::fmt::Result {
    let num_ctrl = mc_gate.num_ctrl_qubits();
    let base = mc_gate.base_gate();

    let name = match (num_ctrl, base) {
        (1, StandardGate::X) => "cx",
        (1, StandardGate::Z) => "cz",
        (1, StandardGate::Y) => "cy",
        (1, StandardGate::H) => "ch",
        (1, StandardGate::RX) => "crx",
        (1, StandardGate::RY) => "cry",
        (1, StandardGate::RZ) => "crz",
        (1, StandardGate::Phase) => "cu1",
        (1, StandardGate::CX) => "ccx",
        (1, StandardGate::SWAP) => "cswap",
        (2, StandardGate::X) => "ccx",
        _ => {
            return writeln!(
                output,
                "// Unsupported MCGate: {} controls on {}",
                num_ctrl, base
            );
        }
    };

    let params_str = format_params(op, circuit, param_map);
    let mapped_qs = map_qubits(op, qubit_map);

    writeln!(output, "{}{} {};", name, params_str, mapped_qs.join(","))
}

#[cfg(test)]
#[path = "./dump_test.rs"]
mod dump_test;
