# This code is part of Cqlib.
#
# (C) Copyright China Telecom Quantum Group 2026
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

from typing import Optional

class Parameter:
    """A symbolic parameter used in parameterized quantum circuits (PQC)."""

    def __init__(self, name: str) -> None:
        """Create a symbolic parameter from a name."""
        ...

    @staticmethod
    def from_float(val: float) -> "Parameter":
        """Create a parameter from a float value."""
        ...

    @staticmethod
    def from_expression(expr: str) -> "Parameter":
        """Parse a mathematical expression string into a Parameter.

        Args:
            expr: The expression string to parse (e.g., "theta + 1", "pi/2", "sin(x)").

        Returns:
            A new Parameter representing the parsed expression.
        """
        ...

    @staticmethod
    def pi() -> "Parameter":
        """Returns a new parameter representing the mathematical constant Pi (π)."""
        ...

    @staticmethod
    def e() -> "Parameter":
        """Returns a new parameter representing the mathematical constant Euler's number (e)."""
        ...

    def evaluate(self, bindings: Optional[dict[str, float]] = None) -> float:
        """Evaluates the parameter expression given a set of variable bindings."""
        ...

    def simplify(self, max_iterations: Optional[int] = None) -> "Parameter":
        """Applies algebraic and trigonometric simplification rules."""
        ...

    def derivative(self, var: str) -> "Parameter":
        """Calculate the derivative of the expression with respect to the specified variable."""
        ...

    @property
    def symbols(self) -> list[str]:
        """Retrieves all unique symbols (variables) used in this parameter expression."""
        ...

    # Arithmetic operators
    def __add__(self, other: "Parameter" | float) -> "Parameter": ...
    def __sub__(self, other: "Parameter" | float) -> "Parameter": ...
    def __mul__(self, other: "Parameter" | float) -> "Parameter": ...
    def __truediv__(self, other: "Parameter" | float) -> "Parameter": ...
    def __pow__(self, other: "Parameter" | float) -> "Parameter": ...
    def __neg__(self) -> "Parameter": ...
    def __eq__(self, other: object) -> bool: ...

    # Reverse arithmetic operators
    def __radd__(self, other: float) -> "Parameter": ...
    def __rsub__(self, other: float) -> "Parameter": ...
    def __rmul__(self, other: float) -> "Parameter": ...
    def __rtruediv__(self, other: float) -> "Parameter": ...

    # Mathematical functions
    def sin(self) -> "Parameter": ...
    def cos(self) -> "Parameter": ...
    def tan(self) -> "Parameter": ...
    def asin(self) -> "Parameter": ...
    def acos(self) -> "Parameter": ...
    def atan(self) -> "Parameter": ...
    def exp(self) -> "Parameter": ...
    def ln(self) -> "Parameter": ...
    def log(self, base: Optional["Parameter"] = None) -> "Parameter": ...
    def sqrt(self) -> "Parameter": ...
    def abs(self) -> "Parameter": ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
