# This code is part of Cqlib.
#
# (C) Copyright China Telecom Quantum Group 2026
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http:#www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

from typing import Dict, List, Optional
import numpy as np
from cqlib.circuit import Instruction, StandardGate
from cqlib.compiler import Topology


class InstructionProp:
    def __init__(self, instruction: Instruction, error_rate: float) -> None: ...
    def with_length(self, length: float) -> "InstructionProp": ...
    @property
    def instruction(self) -> Instruction: ...
    @property
    def error_rate(self) -> float: ...
    @property
    def length(self) -> Optional[float]: ...


class QubitProp:
    def __init__(self, readout_error: float) -> None: ...
    def with_prob_meas0_prep1(self, prob: float) -> "QubitProp": ...
    def with_prob_meas1_prep0(self, prob: float) -> "QubitProp": ...
    def with_t1(self, t1: float) -> "QubitProp": ...
    def with_t2(self, t2: float) -> "QubitProp": ...
    def with_frequency(self, frequency: float) -> "QubitProp": ...
    def with_native_instruction(self, prop: InstructionProp) -> "QubitProp": ...
    @property
    def readout_error(self) -> float: ...
    @property
    def t1(self) -> Optional[float]: ...
    @property
    def t2(self) -> Optional[float]: ...
    @property
    def frequency(self) -> Optional[float]: ...
    @property
    def native_instructions(self) -> List[InstructionProp]: ...


class EdgeProp:
    def __init__(self) -> None: ...
    def with_native_instruction(self, prop: InstructionProp) -> "EdgeProp": ...
    @property
    def native_instructions(self) -> List[InstructionProp]: ...


class Device:
    def __init__(self, name: str, topology: Topology) -> None: ...
    def with_native_gates(self, gates: List[Instruction]) -> "Device": ...
    def with_default_t1(self, t1: float) -> "Device": ...
    def with_default_t2(self, t2: float) -> "Device": ...
    def with_default_readout_error(self, error: float) -> "Device": ...
    def with_default_single_qubit_error(self, error: float) -> "Device": ...
    def with_default_two_qubit_error(self, error: float) -> "Device": ...
    def add_qubit_properties(self, qubit: int, props: QubitProp) -> None: ...
    def add_edge_properties(self, control: int, target: int, props: EdgeProp) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def qubits(self) -> List[int]: ...
    @property
    def invalid_qubits(self) -> List[int]: ...
    @property
    def topology(self) -> Topology: ...
    @property
    def native_gates(self) -> List[Instruction]: ...
    def qubit_properties(self, qubit: int) -> Optional[QubitProp]: ...
    def edge_properties(self, control: int, target: int) -> Optional[EdgeProp]: ...
    def get_t1(self, qubit: int) -> Optional[float]: ...
    def get_t2(self, qubit: int) -> Optional[float]: ...
    def get_readout_error(self, qubit: int) -> Optional[float]: ...
    @property
    def default_single_qubit_error(self) -> Optional[float]: ...
    @property
    def default_two_qubit_error(self) -> Optional[float]: ...


class Layout:
    def __init__(
        self,
        logical: List[int],
        physical: List[int],
        init_map: Optional[Dict[int, int]] = None,
    ) -> None: ...
    @property
    def num_logical(self) -> int: ...
    @property
    def num_ancilla(self) -> int: ...
    @property
    def num_physical(self) -> int: ...
    def get_physical(self, virtual_id: int) -> Optional[int]: ...
    def get_virtual(self, physical_id: int) -> Optional[int]: ...
    @property
    def logical_qubits(self) -> List[int]: ...
    @property
    def ancilla_qubits(self) -> List[int]: ...
    @property
    def physical_qubits(self) -> List[int]: ...
    @property
    def v2p_map(self) -> Dict[int, int]: ...
    @property
    def p2v_map(self) -> Dict[int, int]: ...
    def swap_physical(self, phys_a: int, phys_b: int) -> None: ...


class SingleQubitNoise:
    @staticmethod
    def bit_flip(p: float) -> "SingleQubitNoise": ...
    @staticmethod
    def phase_flip(p: float) -> "SingleQubitNoise": ...
    @staticmethod
    def pauli(px: float, py: float, pz: float) -> "SingleQubitNoise": ...
    @staticmethod
    def depolarizing(p: float) -> "SingleQubitNoise": ...
    @staticmethod
    def amplitude_damping(gamma: float) -> "SingleQubitNoise": ...
    @staticmethod
    def phase_damping(lambda_: float) -> "SingleQubitNoise": ...
    def is_valid(self) -> bool: ...
    def to_kraus(self) -> List[np.ndarray]: ...
    @property
    def kind(self) -> str: ...


class TwoQubitNoise:
    @staticmethod
    def depolarizing(p: float) -> "TwoQubitNoise": ...
    @staticmethod
    def independent(
        q0_noise: SingleQubitNoise, q1_noise: SingleQubitNoise
    ) -> "TwoQubitNoise": ...
    @staticmethod
    def correlated_pauli(op_q0: str, op_q1: str, p: float) -> "TwoQubitNoise": ...
    def is_valid(self) -> bool: ...
    def to_kraus(self) -> List[np.ndarray]: ...
    @property
    def kind(self) -> str: ...


class ReadoutError:
    def __init__(self, p_0_given_1: float, p_1_given_0: float) -> None: ...
    @property
    def p_0_given_1(self) -> float: ...
    @property
    def p_1_given_0(self) -> float: ...
    def is_valid(self) -> bool: ...


class OperationKey:
    @staticmethod
    def new_single(gate: StandardGate, q0: int) -> "OperationKey": ...
    @staticmethod
    def new_double(gate: StandardGate, q0: int, q1: int) -> "OperationKey": ...
    @staticmethod
    def new_triple(gate: StandardGate, q0: int, q1: int, q2: int) -> "OperationKey": ...
    @property
    def qubits(self) -> List[int]: ...
    @property
    def gate(self) -> StandardGate: ...
    def __hash__(self) -> int: ...
    def __eq__(self, value: object) -> bool: ...


class NoiseModel:
    def __init__(self) -> None: ...
    def add_readout_error(self, qubit: int, error: ReadoutError) -> None: ...
    def add_single_qubit_error(
        self, gate: StandardGate, qubit: int, noise: SingleQubitNoise
    ) -> None: ...
    def add_two_qubit_error(
        self, gate: StandardGate, q0: int, q1: int, noise: TwoQubitNoise
    ) -> None: ...
    def get_readout_error(self, qubit: int) -> Optional[ReadoutError]: ...
    def get_single_qubit_errors(
        self, key: OperationKey
    ) -> Optional[List[SingleQubitNoise]]: ...
    def get_two_qubit_errors(self, key: OperationKey) -> Optional[List[TwoQubitNoise]]: ...


class Outcome:
    def __init__(self, bitstring: str) -> None: ...
    @staticmethod
    def from_bitstring(bitstring: str) -> "Outcome": ...
    def is_one(self, index: int) -> bool: ...
    def to_bitstring(self, num_qubits: int) -> str: ...
    @property
    def chunks(self) -> List[int]: ...
    def __hash__(self) -> int: ...
    def __eq__(self, value: object) -> bool: ...


class Status:
    @staticmethod
    def queued() -> "Status": ...
    @staticmethod
    def running() -> "Status": ...
    @staticmethod
    def completed() -> "Status": ...
    @staticmethod
    def failed(error_msg: str, error_code: int) -> "Status": ...
    @staticmethod
    def cancelled() -> "Status": ...
    @property
    def kind(self) -> str: ...
    @property
    def error_msg(self) -> Optional[str]: ...
    @property
    def error_code(self) -> Optional[int]: ...
    def is_terminal(self) -> bool: ...
    def is_success(self) -> bool: ...


class ExecutionResult:
    def __init__(
        self,
        task_id: str,
        qubits: List[int],
        shots: int,
        num_qubits: int,
        backend: Optional[str] = None,
    ) -> None: ...
    def start(self) -> None: ...
    def finish(self, counts: Dict[str, int]) -> None: ...
    def fail(self, msg: str, code: int) -> None: ...
    def cancel(self) -> None: ...
    def calc_probabilities(self) -> None: ...
    @property
    def task_id(self) -> str: ...
    @property
    def shots(self) -> int: ...
    @property
    def num_qubits(self) -> int: ...
    @property
    def qubits(self) -> List[int]: ...
    @property
    def status(self) -> Status: ...
    @property
    def created_at(self) -> str: ...
    @property
    def started_at(self) -> Optional[str]: ...
    @property
    def finished_at(self) -> Optional[str]: ...
    @property
    def backend(self) -> Optional[str]: ...
    @property
    def counts(self) -> Dict[str, int]: ...
    @property
    def probabilities(self) -> Optional[Dict[str, float]]: ...


__all__ = [
    "Topology",
    "InstructionProp",
    "QubitProp",
    "EdgeProp",
    "Device",
    "Layout",
    "SingleQubitNoise",
    "TwoQubitNoise",
    "ReadoutError",
    "OperationKey",
    "NoiseModel",
    "Outcome",
    "Status",
    "ExecutionResult",
]
